[package]
name = "minikv"
version = "1.0.0"
edition = "2024"
description = "Mini key-value store persistente con log y snapshots"
authors = ["Taller de Programacion"]

[[bin]]
name = "minikv-server"
path = "src/bin/server.rs"

[[bin]]
name = "minikv-client"
path = "src/bin/client.rs"

[dependencies]
